### ISSUE TITLE
Automatic contract verification does not work

### ISSUE THREAD

**Issue by hung-native** [Tenderly/hardhat-tenderly#116] opened 2023-02-16 09:54 UTC
I opened a new hardhat project and follow the instructions of "Automatic Contract Verification". Using the sample `Greeter.sol` contract, the `automatic.ts` deployment script and deploy on tenderly fork.
https://docs.tenderly.co/monitoring/smart-contract-verification/verifying-contracts-using-the-tenderly-hardhat-plugin/automatic-contract-verification

It gives the following error
```
2023-02-16 09:51:39.271 ERROR Service =>Unexpected error occurred. 
  Error reason 500 Internal Server Error. 
  Error context: failed to verify contract
2023-02-16 09:51:39.279 ERROR Service =>Error in hardhat-tenderly: Verification failed. There was an error during the API request, please contact support with the above error.
{Greeter} deployed to 0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990
```

**Comment by dule-git** [comment] 2023-03-20 13:24
Hello, we are sorry for such an uninformative error. We are working on exposing our errors in a more readable manner.

The most common mistake that can cause this error is:
- Providing your own account slug instead of organisation's account slug. Check [here](https://github.com/Tenderly/hardhat-tenderly/tree/master/packages/tenderly-hardhat#verification-modes).

Also, if you haven't, you should first read the .README file of the hardhat-tenderly repo [here](https://github.com/Tenderly/hardhat-tenderly/tree/master/packages/tenderly-hardhat). Then try and go through the examples from their own .README file [here](https://github.com/Tenderly/hardhat-tenderly/tree/master/examples/contract-verification).

**Comment by MysticDakra** [comment] 2024-09-04 23:21
I am getting the same issue

**Comment by dule-git** [comment] 2024-10-25 08:40
Hello, 

I have tried to reproduce what you described, but failed.
That is, I successfully managed to set up `hardhat-tenderly` by reading the documentation that you provided.

Since a lot of time has passed and the docs have been updated I'm going to close this issue.
If you are still having problems please write to our support or open another github issue. 

Thanks!

**Closed by dule-git** 2024-10-25 08:40 UTC
