### ISSUE TITLE
gitprotocol-v2.txt

### ISSUE THREAD

**Issue by Hawthorne001** [Tenderly/hardhat-tenderly#199] opened 2024-08-26 06:13 UTC
content://com.microsoft.sharepoint.content.fileopen/FILE_CACHE/TylerHawthorne%40MainH.onmicrosoft.com%20(MainbaseT)/RecentDocumentsUri/59/gitprotocol-v2.txt

**Comment by dule-git** [comment] 2024-10-24 12:27
The issue is not described well, closing the issue.

**Closed as completed by dule-git** 2024-10-24 12:27 UTC
