### ISSUE TITLE
Llluuo

### ISSUE THREAD

**Issue by ibrahimkhled** [Tenderly/hardhat-tenderly#241] opened 2024-10-10 10:42 UTC
https://github.com/Tenderly/examples-web3-actions/blob/main/multisig-wallet%2Fweb3-actions%2Fabi%2FToken.json#L2-L164

**Comment by dule-git** [comment] 2024-10-24 12:27
The issue is not described well, closing the issue.

**Closed by dule-git** 2024-10-24 12:27 UTC
