### ISSUE TITLE
yarn chain command: "SyntaxError: Invalid or unexpected token"

### ISSUE THREAD

**Issue by WildSaoFeng** [Tenderly/hardhat-tenderly#21] opened 2021-12-16 11:21 UTC
Hi, I am using hardhat to deploy the test project. When I finished downloading the repo, ran `yarn install` and then `yarn chain`, it will return an error showing as below:

```
yarn run v1.22.15
$ yarn workspace @scaffold-eth/hardhat chain
$ hardhat node --network hardhat --no-deploy
An unexpected error occurred:

/Users/[username]/Desktop/Hackathon/scaffold-eth/packages/hardhat/node_modules/@tenderly/hardhat-tenderly/node_modules/fs-extra/lib/remove/rimraf.js:268
    } else if (er.code === 'E
                           ^^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/[username]/Desktop/Hackathon/scaffold-eth/packages/hardhat/node_modules/@tenderly/hardhat-tenderly/node_modules/fs-extra/lib/remove/index.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/[username]/.nvm/versions/node/v16.13.0/bin/node
Arguments: /usr/local/lib/node_modules/yarn/lib/cli.js chain
Directory: /Users/[username]/Desktop/Hackathon/scaffold-eth/packages/hardhat
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

I am running on MacOS Big Sur 11.5.1 with M1 chip. 

Node Version: v16.13.0

Anyone gets any idea where goes wrong?

**Comment by Riphal** [comment] 2021-12-21 11:54
Hi, can you send us a version of `@tenderly/hardhat-tenderly` that you use or the whole project if it is public.
Because I can't reproduce this bug.

**Comment by WildSaoFeng** [comment] 2021-12-31 06:25
Hi Riphal, Thanks for your reply! I am using this project:
https://github.com/scaffold-eth/scaffold-eth

and in that repo, it's using `"@tenderly/hardhat-tenderly": "^1.0.10",`

I searched for the error, it may be a cause of encoding issue on my laptop, I will check this in these days

**Comment by dule-git** [comment] 2024-10-24 14:01
Hello @WildSaoFeng,

Since a lot of versions of `hardhat-tenderly` have been released and there hasn't been any activity on this issue, I'll close it.

Please feel free to reopen it if you are still having the error.

**Closed by dule-git** 2024-10-24 14:01 UTC
